// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTMrFwK5QdbHjzEuWKZvSlKIbVNUs-vA',
    appId: '1:436882447188:web:bd82f2e2d0893c5cad06c1',
    messagingSenderId: '436882447188',
    projectId: 'flashfuel-2c9c2',
    authDomain: 'flashfuel-2c9c2.firebaseapp.com',
    storageBucket: 'flashfuel-2c9c2.firebasestorage.app',
    measurementId: 'G-LM7HL3238R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PeWY9eggnj6PedWT5Y3efpXYe9FjsKs',
    appId: '1:436882447188:android:23c7685b3a033ba2ad06c1',
    messagingSenderId: '436882447188',
    projectId: 'flashfuel-2c9c2',
    storageBucket: 'flashfuel-2c9c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1xs8EYdzTB83aweSRYVFkM5Dby7yMqXo',
    appId: '1:436882447188:ios:e5cada2eb743b5d4ad06c1',
    messagingSenderId: '436882447188',
    projectId: 'flashfuel-2c9c2',
    storageBucket: 'flashfuel-2c9c2.firebasestorage.app',
    iosBundleId: 'com.example.demoFlashFuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1xs8EYdzTB83aweSRYVFkM5Dby7yMqXo',
    appId: '1:436882447188:ios:e5cada2eb743b5d4ad06c1',
    messagingSenderId: '436882447188',
    projectId: 'flashfuel-2c9c2',
    storageBucket: 'flashfuel-2c9c2.firebasestorage.app',
    iosBundleId: 'com.example.demoFlashFuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsTMrFwK5QdbHjzEuWKZvSlKIbVNUs-vA',
    appId: '1:436882447188:web:a748568be5df60d5ad06c1',
    messagingSenderId: '436882447188',
    projectId: 'flashfuel-2c9c2',
    authDomain: 'flashfuel-2c9c2.firebaseapp.com',
    storageBucket: 'flashfuel-2c9c2.firebasestorage.app',
    measurementId: 'G-9PD3CZGDM3',
  );
}
